name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/merilevente/webtest-azure:$IMAGE_TAG --tag ghcr.io/merilevente/webtest-azure:latest
        docker login ghcr.io -u MeriLevente -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/merilevente/webtest-azure:$IMAGE_TAG
        docker push ghcr.io/merilevente/webtest-azure:latest
        
